var EQUATIONS_DATA = {
  "AngleBar": "\\left\\langle\\large{x}}\\right\\vert",
  "BarAngle": "\\left\\vert\\large{x}}\\right\\rangle",
  "BottomCurlyBracket": "\\underbrace{\\large{x}}_{\\large{y}}",
  "BottomSquareBracket": "",
  "Ceiling": "\\left\\lceil\\large{x}\\right\\rceil",
  "CurlyBracket": "\\left\\{\\large{x}\\right\\}",
  "DoubleArrowBarBracket": "\\left\\langle\\large{x}|\\large{y}}\\right\\rangle",
  "DoubleBar": "\\left\\|\\large{x}\\right\\|",
  "Floor": "\\left\\lfloor\\large{x}\\right\\rfloor ",
  "LeftAngle": "\\langle\\large{x}",
  "LeftBar": "\\left|\\large{x}",
  "LeftCurlyBracket": "\\left\\{\\large{x}",
  "LeftDoubleBar": "||\\large{x}",
  "LeftLeftSquareBracket": "[\\large{x}[",
  "LeftParenthesis": "(\\large{x}",
  "LeftSquareBar": "⟦\\large{x}",
  "LeftSquareBracket": "[\\large{x}",
  "Parentheses": "(\\large{x})",
  "ParenthesisSquare": "(\\large{x}]",
  "PointingAngles": "\\left\\langle\\large{x}\\right\\rangle",
  "RightAngle": "\\large{x}\\rangle",
  "RightBar": "\\large{x}|",
  "RightCurlyBracket": "\\large{x}}",
  "RightDoubleBar": "\\large{x}||",
  "RightLeftSquareBracket": "]\\large{x}[",
  "RightParenthesis": "\\large{x})",
  "RightRightSquareBracket": "]\\large{x}]",
  "RightSquareBar": "\\large{x}⟧",
  "RightSquareBracket": "\\large{x}]",
  "SingleBar": "\\left|\\large{x}\\right|",
  "SquareBar": "⟦\\large{x}⟧",
  "SquareBracket": "[\\large{x}]",
  "SquareParenthesesBracket": "[(\\large{x}])",
  "SquareParenthesis": "[\\large{x})",
  "TopCurlyBracket": "\\overbrace{\\large{x}}^{\\large{y}}",
  // "TopSquareBracket": "", \overbracket{abc}
  "TopSquareBracket": "",
  "ArrowDoubleBottom": "\\overleftrightarrow{\\large{x}}",
  "ArrowDoubleBottomTop": "\\xleftrightarrow[\\large{y}]{\\large{x}}",
  "ArrowDoubleTop": "\\underleftrightarrow{\\large{x}}",
  "LeftBottom": "\\overleftarrow{\\large{x}}",
  "LeftBottomTop": "\\xleftarrow[\\large{x}]{\\large{y}}",
  "LeftTop": "\\underleftarrow{\\large{x}}",
  "RightBottom": "\\overrightarrow{\\large{x}}",
  "RightBottomTop": "\\xrightarrow[\\large{x}]{\\large{y}}",
  "RightLeftBottom": "\\xtofrom[\\large{x}]{}",
  "RightLeftBottomTop": "\\xtofrom[\\large{x}]{\\large{y}}",
  "RightLeftHarpBottom": "\\xrightleftharpoons[\\large{x}]{}",
  "RightLeftHarpBottomTop": "\\xrightleftharpoons[\\large{x}]{\\large{y}}",
  "RightLeftHarpTop": "\\xrightleftharpoons[]{\\large{y}}",
  "RightLeftTop": "\\xtofrom[]{\\large{y}}",
  "RightSmallLeftBottom": "",
  "RightSmallLeftBottomTop": "",
  "RightSmallLeftHarpBottom": "\\xrightequilibrium[\\large{x}]{}",
  "RightSmallLeftHarpBottomTop": "\\xrightequilibrium[\\large{x}]{\\large{y}}",
  "RightSmallLeftHarpTop": "\\xrightequilibrium[]{\\large{x}}",
  "RightSmallLeftTop": "",
  "RightTop": "",
  "SmallRightLeftBottomTop": "",
  "SmallRightLeftHarpBottom": "\\xleftequilibrium[\\large{x}]{}",
  "SmallRightLeftHarpBottomTop": "\\xleftequilibrium[\\large{x}]{\\large{y}}",
  "SmallRightLeftHarpTop": "\\xleftequilibrium[]{\\large{y}}",
  "SmallRightLeftTop": "",
  "coProduct": "\\coprod{\\large{x}}",
  "coProductBottom": "\\coprod_{\\large{x}}{\\large{y}}",
  "coProductBottomTop": "\\coprod_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "coProductSub": "\\coprod\\limits_{\\large{x}}{\\large{y}}",
  "coProductSubSuper": "\\coprod\\limits_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "intersection": "\\bigcap{\\large{x}}",
  "intersectionBottom": "\\bigcap_{\\large{x}}{\\large{y}}",
  "intersectionBottomTop": "\\bigcap_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "intersectionSub": "\\bigcap\\limits_{\\large{x}}{\\large{y}}",
  "intersectionSubSuper": "\\bigcap\\limits_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "product": "\\prod{\\large{x}}",
  "productBottom": "\\prod_{\\large{x}}{\\large{y}}",
  "productBottomTop": "\\prod_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "productSub": "\\prod\\limits_{\\large{x}}{\\large{y}}",
  "productSubSuper": "\\prod\\limits_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "sum": "\\sum{\\large{x}}",
  "sumBottom": "\\sum_{\\large{x}}{\\large{y}}",
  "sumBottomTop": "\\sum_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "sumSub": "\\sum\\limits_{\\large{x}}{\\large{y}}",
  "sumSubSuper": "\\sum\\limits_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "union": "\\bigcup{\\large{x}}",
  "unionBottom": "\\bigcup_{\\large{x}}{\\large{y}}",
  "unionBottomTop": "\\bigcup_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "unionSub": "\\bigcup\\limits_{\\large{x}}{\\large{y}}",
  "unionSubSuper": "\\bigcup\\limits_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "SingleBottom": "\\int\\limits_{\\large{x}}{\\large{z}}",
  "SingleBottomTop": "\\int\\limits_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "SingleSimple": "\\int{\\large{z}}",
  "SingleSub": "\\int_{\\large{x}}{\\large{z}}",
  "SingleSubSuper": "\\int_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "DoubleBottom": "\\iint\\limits_{\\large{x}}{\\large{z}}",
  "DoubleBottomTop": "\\iint\\limits_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "DoubleSimple": "\\iint{\\large{z}}",
  "DoubleSub": "\\iint_{\\large{x}}{\\large{z}}",
  "DoubleSubSuper": "\\iint_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "TripleBottom": "\\iiint\\limits_{\\large{x}}{\\large{z}}",
  "TripleBottomTop": "\\iiint\\limits_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "TripleSimple": "\\iiint{\\large{z}}",
  "TripleSub": "\\iiint_{\\large{x}}{\\large{z}}",
  "TripleSubSuper": "\\iiint_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "ClockBottom": "\\oint\\limits_{\\large{x}}{\\large{z}}",
  "ClockBottomTop": "\\oint\\limits_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "ClockSimple": "\\oint{\\large{z}}",
  "ClockSub": "\\oint_{\\large{x}}{\\large{z}}",
  "ClockSubSuper": "\\oint_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "SurfaceBottom": "\\oiint\\limits_{\\large{x}}{\\large{z}}",
  "SurfaceBottomTop": "\\oiint\\limits_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "SurfaceSimple": "\\oiint{\\large{z}}",
  "SurfaceSub": "\\oiint_{\\large{x}}{\\large{z}}",
  "SurfaceSubSuper": "\\oiint_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "VolumeBottom": "\\oiiint\\limits_{\\large{x}}{\\large{z}}",
  "VolumeBottomTop": "\\oiiint\\limits_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "VolumeSimple": "\\oiiint{\\large{z}}",
  "VolumeSub": "\\oiiint_{\\large{x}}{\\large{z}}",
  "VolumeSubSuper": "\\oiiint_{\\large{x}}^{\\large{y}}{\\large{z}}",
  "Sub": "{\\large{y}}_{\\large{x}}",
  "SubLeft": "",
  "SubSuper": "{\\large{x}}_{\\large{y}}^{\\large{z}}",
  "SubSuperLeft": "",
  "Super": "{\\large{x}}^{\\large{y}}",
  "SuperLeft": "",
  "BigBottom": "\\underset{\\large{x}}{\\large{y}}",
  "BigBottomTop": "\\overset{\\large{x}}{\\underset{\\large{y}}{\\large{z}}}",
  "BigSub": "\\large{x}_{\\large{y}}",
  "BigSubSuper": "\\large{x}^\\large{y}_{\\large{z}}",
  "BigSuper": "\\large{x}^{\\large{y}}",
  "BigTop": "\\overset{\\large{x}}{\\large{y}}",
  "CompositeBottom": "\\underset{\\large{x}}{\\large{y}}",
  "CompositeBottomTop": "\\overset{\\large{x}}{\\underset{\\large{y}}{\\large{z}}}",
  "CompositeTop": "\\overset{\\large{x}}{\\large{y}}",
  "Div": "\\frac{\\large{x}}{\\large{y}}",
  "DivDoubleBar": "\\xlongequal[\\large{x}]{\\large{y}}",
  "DivHoriz": "{\\large{x}}/{\\large{y}}",
  "DivMath": "",
  "DivMathInverted": "",
  "DivMathInvertedWithBottom": "",
  "DivMathWithTop": "",
  "DivSlant": "",
  "DivTriangleExpanding": "",
  "DivTriangleFixed": "",
  "DivTripleBar": "",
  "nRoot": "\\sqrt[\\large{x}]{\\large{y}}",
  "SmallDiv": "",
  "SmallDivHoriz": "",
  "SmallDivSlant": "",
  "SqRoot": "\\sqrt{\\large{x}}",
  "2cellColumn": "\\begin{matrix} \\large{a}_{11} \\\\ \\large{a}_{21} \\end{matrix}",
  "2cellRow": "\\begin{matrix} \\large{a}_{11} & \\large{a}_{12} \\end{matrix}",
  "2Square": "\\begin{matrix} \\large{a}_{11} & \\large{a}_{12} \\\\ \\large{a}_{21} & \\large{a}_{22} \\end{matrix}",
  "3cellColumn": "\\begin{matrix} \\large{a}_{11} \\\\ \\large{a}_{21} \\\\ \\large{a}_{31} \\end{matrix} ",
  "3cellRow": "\\begin{matrix} \\large{a}_{11} & \\large{a}_{12} & \\large{a}_{13}\\end{matrix}",
  "3Square": "\\begin{matrix} \\large{a}_{11} & \\large{a}_{12} & \\large{a}_{13} \\\\ \\large{a}_{21} & \\large{a}_{22} & \\large{a}_{23} \\\\ \\large{a}_{31} & \\large{a}_{32} & \\large{a}_{33} \\end{matrix}",
  "column": "\\begin{pmatrix} \\large{a}_1 \\\\ \\vdots \\\\ \\large{a}_n \\end{pmatrix}",
  "custom": "\\begin{pmatrix} \\large{a}_{11} & \\ldots & \\large{a}_{1c} \\\\ \\vdots & \\ddots & \\vdots \\\\ \\large{a}_{r1} & \\ldots & \\large{a}_{rc} \\end{pmatrix}",
  "row": "\\begin{pmatrix} \\large{a}_1 & \\ldots & \\large{a}_n \\end{pmatrix}",
  "BoxAll": "\\boxed{\\large{x}}",
  "BoxLeftBottom": "",
  "BoxLeftTop": "",
  "BoxRightBottom": "",
  "BoxRightTop": "",
  "bottomBar": "\\underset{-}{\\large{x}}",
  "bottomDoubleArrow": "\\underleftrightarrow{\\large{x}}",
  "bottomDoubleBar": "\\underset{\\large{=}}{\\large{x}}",
  "bottomLeftArrow": "\\underleftarrow{\\large{x}}",
  "bottomLeftHalfArrow": "\\underset{\\large{\\leftharpoondown}}{\\large{x}}",
  "bottomRightArrow": "\\underrightarrow{\\large{x}}",
  "bottomRightHalfArrow": "\\underset{\\large{\\rightharpoondown}}{\\large{x}}",
  "cross": "\\xcancel{\\large{x}}",
  "hat": "\\hat{\\large{x}}",
  "leftCross": "\\bcancel{\\large{x}}",
  "parenthesis": "\\overset{\\frown}{\\large{x}}",
  "rightCross": "\\cancel{\\large{x}}",
  "strikeThrough": "",
  "tilde": "\\tilde{\\large{x}}",
  "topBar": "\\overset{-}{\\large{x}}",
  "topDoubleArrow": "\\overleftrightarrow{\\large{x}}",
  "topDoubleBar": "\\overset{\\large{=}}{\\large{x}}",
  "topLeftArrow": "\\overleftarrow{\\large{x}}",
  "topLeftHalfArrow": "\\overset{\\large{\\leftharpoondown}}{\\large{x}}",
  "topRightArrow": "\\overrightarrow{\\large{x}}",
  "topRightHalfArrow": "\\overset{\\large{\\rightharpoondown}}{\\large{x}}",
  "tortoise": "\\overgroup{\\large{x}}",
  "CharacterAcuteAccent": "\\large{x}'",
  "CharacterBottomBar": "\\underset{-}{\\large{x}}",
  "CharacterBottomBreve": "\\underset{\\smile}{\\large{x}}",
  "CharacterBottomDDot": "\\underset{\\Large{..}}{\\large{x}}",
  "CharacterBottomDot": "\\underset{\\Large{.}}{\\large{x}} ",
  "CharacterBottomDoubleArrow": "\\underleftrightarrow{\\large{x}} ",
  "CharacterBottomFourDot": "\\underset{\\Large{....}}{\\large{x}}",
  "CharacterBottomInvertedBreve": "\\underset{\\frown}{\\large{x}}",
  "CharacterBottomLeftArrow": "\\underset{\\leftarrow}{\\large{x}}",
  "CharacterBottomLeftHarpoon": "\\underset{\\leftharpoondown}{\\large{x}}",
  "CharacterBottomRightArrow": "\\underset{\\rightarrow}{\\large{x}}",
  "CharacterBottomRightHarpoon": "\\underset{\\rightharpoondown}{\\large{x}}",
  "CharacterBottomTDot": "\\underset{\\large{...}}{\\large{x}}",
  "CharacterBottomTilde": "\\underset{\\sim }{\\large{x}} ",
  "CharacterCross": "\\xcancel{\\large{x}}",
  "CharacterDoublePrime": "\\large{x}''",
  "CharacterDoubleStrikeThrough": "",
  "CharacterGraveAccent": "\\large{x}`",
  "CharacterLeftCross": "\\bcancel{\\large{x}}",
  "CharacterLeftUprightCross": "\\bcancel{\\large{x}}",
  "CharacterNone": "\\large{x}",
  "CharacterPrime": "\\large{x}'",
  "CharacterReverseDoublePrime": "\\large{x}``",
  "CharacterReversePrime": "\\large{x}`",
  "CharacterRightCross": "\\cancel{\\large{x}}",
  "CharacterRightUprightCross": "\\cancel{\\large{x}}",
  "CharacterStrikeThrough": "",
  "CharacterTopBar": "\\overset{-}{\\large{x}}",
  "CharacterTopBreve": "\\overset{\\smile}{\\large{x}}",
  "CharacterTopCaron": "\\check{\\large{x}}",
  "CharacterTopCircumflex": "\\hat{\\large{x}}",
  "CharacterTopDDot": "\\ddot{\\large{x}} ",
  "CharacterTopDot": "\\dot{\\large{x}} ",
  "CharacterTopDoubleArrow": "\\overleftrightarrow{\\large{x}}",
  "CharacterTopFourDot": "\\overset{\\Large{....}}{\\large{x}}",
  "CharacterTopInvertedBreve": "\\overset{\\frown}{\\large{x}}",
  "CharacterTopLeftArrow": "\\overset{\\leftarrow}{\\large{x}}",
  "CharacterTopLeftHarpoon": "\\overset{\\leftharpoondown}{\\large{x}}",
  "CharacterTopRightArrow": "\\overset{\\rightarrow}{\\large{x}}",
  "CharacterTopRightHarpoon": "\\overset{\\rightharpoondown}{\\large{x}}",
  "CharacterTopRightRing": "\\large{x}^{\\circ}",
  "CharacterTopRing": "\\overset{\\circ}{\\large{x}}",
  "CharacterTopTDot": "\\overset{\\Large{...}}{\\large{x}}",
  "CharacterTopTilde": "\\tilde{\\large{x}} ",
  "CharacterTriplePrime": "\\large{x}'''",
  "CharacterVDoubleStrikeThrough": "",
  "CharacterVStrikeThrough": "",
  "Application_1": "A",
  "Application_2": "A_{\\large{x}}",
  "Application_3": "\\hat{A}",
  "Application_4": "\\bar{A}",
  "Application_5": "\\hat{A}_{\\large{x}}",
  "Application_6": "\\bar{A}_{\\large{x}}",
  "function_1": "\\large{x}",
  "function_2": "f({\\large{x}}})",
  "function_3": "\\bar{\\large{x}}",
  "function_4": "f(\\bar{\\large{x}})",
  "function_5": "f_{\\large{x}}(\\bar{\\large{y}})",
  "function_6": "P_{\\large{x}}",
  "function_7": "G_{\\large{x}}",
  "function_8": "G_{\\large{x}}(\\large{x})",
  "function_9": "f(\\large{x})",
  "function_10": "ECF(\\large{x})",
  "function_11": "ECF({\\large{x})",
  "function_12": "f_{\\large{x}}(\\bar{\\large{y}}_{z})",
  "function_13": "\\large{x}_{z}",
  "function_14": "f_{\\large{x}}(y)",
  "Relationship_1": "\\sim",
  "Relationship_2": "\\alpha",
  "Relationship_3": "\\Rightarrow",
  "Relationship_4": "\\Leftarrow",
  "Relationship_5": "\\Leftrightarrow",
  "Relationship_6": "\\geq",
  "Relationship_7": "\\gt",
  "Relationship_8": "\\lt",
  "Relationship_9": "=",
  "Relationship_10": "\\leq",
  "word_1": "\\large{W}",
  "word_2": "\\large{W}_{\\large{x}}",
  "word_3": "\\hat{\\large{W}}",
  "word_4": "\\hat{\\large{W}}_{\\large{x}}",
  "word_5": "\\bar{\\large{W}}",
  "word_6": "\\large{S}(\\large{w})",
  "word_7": "\\large{S}_{\\large{x}}(\\large{w})",
  "word_8": "\\large{G}(\\large{w})",
  "word_9": "\\large{D}(\\large{w})",
  "word_10": "\\large{D}(\\hat{\\large{w}})",
  "word_11": "\\large{G}_{\\large{x}}(\\large{w})",
  "word_12": "\\large{S}(\\bar{\\large{w}})",
  "word_13": "\\large{G}(\\bar{\\large{w}})",
  "Theory_1": "\\large{K}_{\\large{T}}",
  "Theory_2": "\\large{i}_{\\large{T}}",
  "Theory_3": "\\large{I_T}",
  "Theory_4": "\\large{E_T}",
  "Theory_5": "\\large{P_T}",
  "Theory_6": "\\large{M_T}",
  "Theory_7": "\\large{E_{S_{T}}}",
  "Theory_8": "\\large{W_T}",
  "Theory_9": "\\large{G_T}",
  "Theory_10": "\\large{X_T}",
  "Theory_11": "\\large{U_T}",
  "Theory_Dropdown_1": "\\large{T_1}",
  "Theory_Dropdown_2": "\\large{T_2}",
  "Theory_Dropdown_3": "\\large{T_3}",
  "Theory_Dropdown_4": "\\large{T_4}",
  "Theory_Dropdown_5": "\\large{T_5}",
  "Theory_Dropdown_6": "\\large{T_6}",
  "Theory_Dropdown_7": "\\large{T_7}",
  "Theory_Dropdown_8": "\\large{T_8}",
  "Theory_Dropdown_9": "\\large{T_9}",
  "Theory_Dropdown_10": "\\large{T_{10}}",
  "Theory_Dropdown_11": "\\large{T}",
  "Theory_Dropdown_12": "\\large{T}_{\\large{x}}",
  "Theory_Dropdown_13": "\\large{A}",
  "Theory_Dropdown_14": "\\large{A}'",
  "Theory_Dropdown_15": "\\large{A}'|_{\\Large{t_{x}}}",
  "Theory_Dropdown_16": "\\large{A}'_{\\Large{x}}",
  "Fundamental_1": "f_{\\large{K}_{\\large{T}}}",
  "Fundamental_2": "f_{\\large{i}_{\\large{T}}}",
  "Fundamental_3": "f_{\\large{I_{T}}}",
  "Fundamental_4": "f_{\\large{E_{T}}}",
  "Fundamental_5": "f_{\\large{P_{T}}}",
  "Fundamental_6": "f_{\\large{M_{T}}}",
  "Fundamental_7": "f_{\\large{E_{S_{T}}}}",
  "Fundamental_8": "f_{\\large{W_{T}}}",
  "Fundamental_9": "f_{\\large{G_{T}}}",
  "Fundamental_10": "f_{\\large{X_{T}}}",
  "Fundamental_11": "f_{\\large{U_{T}}}",
  "Fundamental_Dropdown_1": "f_{\\large{T_{1}}}",
  "Fundamental_Dropdown_2": "f_{\\large{T_{2}}}",
  "Fundamental_Dropdown_3": "f_{\\large{T_{3}}}",
  "Fundamental_Dropdown_4": "f_{\\large{T_{4}}}",
  "Fundamental_Dropdown_5": "f_{\\large{T_{5}}}",
  "Fundamental_Dropdown_6": "f_{\\large{T_{6}}}",
  "Fundamental_Dropdown_7": "f_{\\large{T_{7}}}",
  "Fundamental_Dropdown_8": "f_{\\large{T_{8}}}",
  "Fundamental_Dropdown_9": "f_{\\large{T_{9}}}",
  "Fundamental_Dropdown_10": "f_{\\large{T_{10}}}",
  "Fundamental_Dropdown_11": "f_{\\large{T}}",
  "Fundamental_Dropdown_12": "f_{\\large{T}_{\\large{x}}}",
  "Fundamental_Dropdown_13": "f_{\\large{A}}",
  "Fundamental_Dropdown_14": "f_{\\large{A}'}",
  "Dropdown_Function_1": "\\mathcal{\\large{L}(\\large{t})}",
  "Dropdown_Function_2": "\\large{h(_{t})}",
  "Dropdown_Function_3": "\\large{u({t})}",
  "Dropdown_Function_4": "\\large{h(_{t})+u({t})}",
  "Dropdown_Function_5": "\\sum\\limits_{\\large{n=1}}^{\\large{\\infty}}{\\large{h_{n}(t)}}",
  "Dropdown_Function_6": "\\sum\\limits_{\\large{m=0}}^{\\large{M}}{\\large{u_{m}(t)}}",
  "Dropdown_Function_7": "Int\\left\\{{\\large{x}}\\right\\}",
  "Dropdown_Function_8": "\\bar{\\large{u}}(t)",
  "Dropdown_Function_9": "\\bar{\\large{u}}_{\\large{x}}(t)",
  "Dropdown_Function_10": "\\large{h}_{\\large{x}}(t)",
  "Dropdown_Time_1": "\\large{t_{0}}",
  "Dropdown_Time_2": "\\large{t_{0+}}",
  "Dropdown_Time_3": "\\large{t_{0++}}",
  "Dropdown_Time_4": "\\large{t_{1}}",
  "Dropdown_Time_5": "\\large{t_{1}}+{\\large{x}}",
  "Dropdown_Time_6": "\\large{t_{2}}",
  "Dropdown_Time_7": "\\large{t_{2}}+{\\large{x}}",
  "Dropdown_Time_8": "\\large{t_{3}}",
  "Dropdown_Time_9": "\\large{t_{3}}+{\\large{x}}",
  "Dropdown_Time_10": "\\large{t_{4}}",
  "Dropdown_Time_11": "\\large{t_{4}}+{\\large{x}}",
  "Dropdown_Time_12": "\\large{t'}",
  "Derivative_1": "\\frac{\\large{d{a}}}{\\large{dx}}",
  "Derivative_2": "\\frac{\\large{dI}}{\\large{dT}}",
  "Derivative_3": "\\frac{\\large{dM}}{\\large{dT}}",
  "Derivative_4": "\\large{NE}",
  "Derivative_5": "\\large{IE}",
  "Instrument_1": "\\large{I}",
  "Instrument_2": "\\large{M}",
  "Instrument_3": "Tr\\left\\{{T}\\right\\}",
  "Instrument_4": "Tr\\left\\{{\\large{x}}\\right\\}",
  "Instrument_5": "\\large{I}[\\large{u(t)}]",
  "Instrument_6": "\\large{M}[\\large{u(t)}]",
  "Instrument_7": "I[u_{\\large{x}}(t)]",
  "Instrument_8": "M[u_{\\large{x}}(t)]",
  "Stability_1": "\\large{k}",
  "Stability_2": "\\large{x}",
  "Stability_3": "\\large{y}",
  "Stability_4": "\\large{x}_{\\large{x}}",
  "Stability_5": "\\large{y}_{\\large{x}}",
  "Stability_6": "\\large{xy}",
  "Stability_7": "\\large{x}_{\\large{x}}\\large{y}_{\\large{y}}",
  "Stability_8": "\\large{S}",
  "Stability_9": "\\large{S}_{\\large{x}}",
  "Stability_10": "\\Delta{\\large{x}}",
  "Stability_11": "\\bar{\\large{T}}",
  "Stability_12": "\\large{L}",
  "Stability_13": "\\large{G}",
  "Stability_14": "\\Delta{L}",
  "Stability_15": "L_{\\large{x}}",
  "Stability_16": "G_{\\large{x}}",
  "Stability_17": "L|_{t_{\\large{x}}}",
  "Stability_18": "G|_{t_{\\large{x}}}",
  "Stability_19": "\\Delta{G}",
  "Stability_20": "\\Delta{t}",
  "Stability_21": "\\frac{\\Delta{L}}{\\Delta{t}}",
  "Stability_22": "\\frac{\\Delta{G}}{\\Delta{t}} ",
  "Stability_23": "Q",
  "Stability_24": "q",
  "Stability_25": "Q|_{t_{\\large{x}}}",
  "Stability_26": "d",
  "Stability_27": "d_{\\large{x}}",
  "Stability_28": "\\Delta{t}",
  "Stability_29": "\\Delta{t}_{u}",
  "Stability_30": "\\Delta{t}_{d}",
  "Stability_31": "\\Delta{t}_{\\large{x}}",
  "Theorem_Dropdown_1": "\\large{Th}",
  "Theorem_Dropdown_2": "\\large{K_{Th}}",
  "Theorem_Dropdown_3": "\\large{i_{Th}}",
  "Theorem_Dropdown_4": "\\large{I_{Th}}",
  "Theorem_Dropdown_5": "\\large{M_{Th}}",
  "Theorem_Dropdown_6": "\\large{E_{S_{Th}}}",
  "Theorem_Dropdown_7": "\\large{W_{Th}}",
  "Theorem_Dropdown_8": "\\large{G_{Th}}",
  "Theorem_Dropdown_9": "\\large{Th_{n}}",
  "Theorem_Dropdown_10": "\\large{K}_{\\large{Th}_{\\large{x}}}",
  "Theorem_Dropdown_11": "\\large{i}_{\\large{Th}_{\\large{x}}}",
  "Theorem_Dropdown_12": "\\large{I}_{\\large{Th}_{\\large{x}}}",
  "Theorem_Dropdown_13": "\\large{M}_{\\large{Th}_{\\large{x}}}",
  "Theorem_Dropdown_14": "\\large{E}_{\\large{S}_{\\large{Th}_{\\large{x}}}}",
  "Theorem_Dropdown_15": "\\large{W}_{\\large{Th}_{\\large{x}}}",
  "Theorem_Dropdown_16": "\\large{G}_{\\large{Th}_{\\large{x}}}",
  "Theorem_Dropdown_17": "\\large{Th}",
  "Theorem_Dropdown_18": "\\large{Th}_{\\large{x}}",
  "Theorem_Dropdown_19": "\\large{Th}|_{\\large{t}_{\\large{x}}}",
  "Theorem_Dropdown_20": "\\large{Th}_{\\large{g}}",
  "Theorem_Dropdown_21": "\\large{Th}_{\\large{g}}|_{\\large{t}_{\\large{x}}}",
}

var OPERATOR = ["\u00d7", "\u002D", "\u2013", "\u2012", "\u2014", "\u00b7", "\u00f7", "\u00b1",
  "\u00bd", "\u00bc", "\u00be", "\u2200", "\u2202", "\u2203", "\u2204",
  "\u2205", "\u2208", "\u2209", "\u220B", "\u220C", "\u220F", "\u2210",
  "\u2211", "\u2217", "\u221A", "\u221D", "\u221E", "\u2227", "\u2228",
  "\u2229", "\u222A", "\u2234", "\u2235", "\u2237", "\u2238", "\u2264",
  "\u2265", "\u226e", "\u226f", "\u25B3", "\u25B7", "\u25BD", "\u25c8",
  "\u25C9", "\u25CE", "\u25E0", "\u25E1", "\u25EC", "\u211d", "\u2124",
  "\u2102", "\ud835\udd46", "\u2115"]

var GREEKCAPTITAL = ["\u0391", "\u0392", "\u0393", "\u0394", "\u0395", "\u0396", "\u0397",
  "\u0398", "\u0399", "\u039A", "\u039B", "\u039C", "\u039D", "\u039E",
  "\u039F", "\u03A0", "\u03A1", "\u03A3", "\u03A4", "\u03A5", "\u03A6",
  "\u03A7", "\u03A8", "\u03A9"]

var GREEKSMALL = ["\u03B1", "\u03B2", "\u03B3", "\u03B4", "\u03B5", "\u03B6", "\u03B7",
  "\u03B8", "\u03B9", "\u03BA", "\u03BB", "\u03BC", "\u03BD", "\u03BE",
  "\u03BF", "\u03C0", "\u03C1", "\u03C2", "\u03C3", "\u03C4", "\u03C5",
  "\u03C6", "\u03C7", "\u03C8", "\u03C9"]

var ARROW = ["\u2190", "\u2191", "\u2192", "\u2193", "\u2194", "\u2195", "\u2196",
  "\u2197", "\u2198", "\u2199", "\u219A", "\u219B", "\u219C", "\u219D",
  "\u219E", "\u219F", "\u21A0", "\u21A1", "\u21A2", "\u21A3", "\u21A4",
  "\u21A5", "\u21A6", "\u21A7", "\u21A8", "\u21A9", "\u21AA", "\u21AB",
  "\u21AC", "\u21AD", "\u21AE", "\u21AF", "\u21B0", "\u21B1", "\u21B2",
  "\u21B3", "\u21B4", "\u21B5", "\u21B6", "\u21B7", "\u21B8", "\u21B9",
  "\u21BA", "\u21BB", "\u21BC", "\u21BD", "\u21BE", "\u21BF", "\u21C0",
  "\u21C1", "\u21C2", "\u21C3", "\u21C4", "\u21C5", "\u21C6", "\u21C7",
  "\u21C8", "\u21C9", "\u21CA", "\u21CB", "\u21CC", "\u21CD", "\u21CE",
  "\u21CF", "\u21D0", "\u21D1", "\u21D2", "\u21D3", "\u21D4", "\u21D5",
  "\u21D6", "\u21D7", "\u21D8", "\u21D8", "\u21D9", "\u21DA", "\u21DB",
  "\u21DC"]

var OPERATOR_WRAPPER = document.getElementById("listSubMenuEuqationsOperator").querySelector(".list-sub-menu-equations")
var GREEKCAPTITAL_WRAPPER = document.getElementById("listSubMenuEuqationsGreekCaptital").querySelector(".list-sub-menu-equations")
var GREEKSMALL_WRAPPER = document.getElementById("listSubMenuEuqationsGreekSmall").querySelector(".list-sub-menu-equations")
var ARROW_WRAPPER = document.getElementById("listSubMenuEuqationsArrow").querySelector(".list-sub-menu-equations")
OPERATOR.forEach(item => {
  let el = document.createElement('div')
  el.className = "d-flex align-items-start"
  el.textContent = item
  el.addEventListener("click", () => {
    handleEquation(item)
  })
  OPERATOR_WRAPPER.appendChild(el)
})

GREEKCAPTITAL.forEach(item => {
  let el = document.createElement('div')
  el.className = "d-flex align-items-start"
  el.textContent = item
  el.addEventListener("click", () => {
    handleEquation(`\\large{${item}}`)
  })
  GREEKCAPTITAL_WRAPPER.appendChild(el)
})
GREEKSMALL.forEach(item => {
  let el = document.createElement('div')
  el.className = "d-flex align-items-start"
  el.textContent = item
  el.addEventListener("click", () => {
    handleEquation(`\\large{${item}}`)
  })
  GREEKSMALL_WRAPPER.appendChild(el)
})
ARROW.forEach(item => {
  let el = document.createElement('div')
  el.className = "d-flex align-items-start"
  el.textContent = item
  el.addEventListener("click", () => {
    handleEquation(`\\large{${item}}`)
  })
  ARROW_WRAPPER.appendChild(el)
})